FROM nginx:1.21.5

# Customization of the nginx user and group ids in the image. It's 101:101 in
# the base image. Here we use 1000 which is the user id and group id for
# the first-created user on most linux and macOS machines. This can be
# overridden in the docker-compose file or `$ docker build` if needed.
ARG nginx_uid=1000
ARG nginx_gid=1000

# The worker processes in the nginx image run as the user nginx with group
# nginx. This is where we override their respective uid and guid to something
# else that lines up better with file permissions.
# The -o switch allows reusing an existing user id
RUN usermod -u $nginx_uid -o nginx && groupmod -g $nginx_gid -o nginx

# vim: ft=dockerfile
